### ISSUE TITLE
Incorrect local timezone in Grocy

### ISSUE THREAD

**Issue by NekoPavel** [hassio-addons/addon-grocy#362]
# Problem/Motivation

> iCal shows the wrong time when exported due to incorrect PHP timezone
> See #274 and [https://github.com/grocy/grocy/issues/214](https://github.com/grocy/grocy/issues/214) for more info on the issue
>Very easily checked by going to the [/system/time](https://demo.grocy.info/api/system/time) API endpoint

## Expected behavior

> iCal in other calendar apps should display correct time of chores and tasks

## Actual behavior

> iCal shows the chores and tasks as if they were created in UTC

## Steps to reproduce

> Create a chore, use iCal and import it to another calendar manager, the chore will appear at the wrong time

## Proposed changes

> `config.php` in `/usr/share/hassio/addons/data/xxxxxxx_grocy/grocy` needs to have the correct timezone.
> This is what I had to do to mine:
 `<?php`
`    date_default_timezone_set("Europe/Stockholm");`
`?>`
> Is it perhaps possible to populate this automatically with the Home Assistant TZ value?

**Comment by frenck** [comment]
Hmm right, PHP will ignore the system time by default and always uses UTC.

Interestingly enough, seems like Grocy doesn't handle timezones _at all_ (which IMHO is wrong and problematic).

I think changing it, will merely mess with timezone instead of solving anything (it might become even more problematic once Grocy actually starts handling timezones). So, for me, I think I'm split on what the solution should be.

../Frenck
