### ISSUE TITLE
Map config directory inside `addon_config`

### ISSUE THREAD

**Issue by saya6k** [hassio-addons/addon-grocy#430]
# Problem/Motivation

Since `addon_config` is available in Add-ons, we don't need to reinvent the wheels. Just make users customize their own config with `addon_config` option in Home Assistant. No need to make tweak for every option.

## Expected behavior

Map directory `addon_config:rw` in `config.yaml`
While deploying with s6-overlay in user `init-grocy`, check if `/var/www/grocy` directory exist. If it doesn't exist, symlink `/config` with`/var/www/grocy` directory.

## Actual behavior

We can now approach `/addon_configs/a0d7b954-grocy/data/config.php` as customization for Grocy and `/addon_configs/a0d7b954-grocy/public` as customization for Nginx, `/addon_configs/a0d7b954-grocy/data/grocy.db` as database.

What user customize remains when reinstalling add-on or update.

## Proposed changes

With this change, someone who wants advanced features like label printer integration will customize their own config. No need to define every tweaks in `config.yaml`. Someone who wants to migrate Grocy add-on to standalone install can approach sqlite database directly.

Now #411, #409, #410, #425 all solved.

**Comment by valadas** [comment]
That sounds to me like a great idea

**Comment by igorsantos07** [comment]
But....... How's this related to redirect issues from #409?

**Comment by realcanadrian** [comment]
YES PLEASE. I’m melting my brain trying to figure out how to enable the label printer with this addon. The Grocy developer gives us a config.php file for us to modify settings. Why is this file not just exposed for us to use? Or at least support docker environment variables to override options in the config. Again, this is supported in Grocy and I don’t know why it isn’t in the HA addon.

**Comment by realcanadrian** [comment]
This GitHub stale bot is WAY too aggressive. This is a feature request; it doesn’t just become irrelevant because no one has implemented it within a month. Probably at minimum they should stay open for a year or two. Do we really need to come up with some kind of anti-stale bot to fight the stale bot?

**Comment by valadas** [comment]
At the very least, dependabot should be on a longer schedule than the time between maintainer replies/reviews.

**Comment by realcanadrian** [comment]
> I am wondering at this point if this project is still maintained.

Yeah, I’m wondering if the venerable @frenck - being as busy as he is with many important things - is like “the add on works well enough for my purposes”, and further development has not been near the top of his list of things to do. The thing is though… then how does one get anything into the project? Is there anyone else we can contact to approve PRs? It makes sense that one guy can be busy, but it would be really great if someone else could help share the burden. I’m afraid as a non-developer I’m not sure how to be more proactive on that front.

**Comment by igorsantos07** [comment]
The stale bot is terrible on all HA repos. It should only attack when there's no reply AFTER a maintainer interacted. I have a task popping on my phone every 20 or so days to remind me to leave a comment on interested stories, so they don't go stale 🤡 

The HA team should really get more people checking their issue boards, as many of them seem completely abandoned. I know people are busy and all, but HA isn't just Frenck anymore. It's terrible to report a real problem and have no replies in months and months, it just ruins your experience with many bits of HA.

And, on the other side, the Grocy maintainer is simply a rude person. I reported a couple of stuff on his side and I got almost spit on the face. So, don't ever wait for any actual fix coming from there, unless it is affecting HIS use case - which doesn't include HA, which he seems to almost despise.

**Comment by igorsantos07** [comment]
And there we go again...

**Comment by realcanadrian** [comment]
> And, on the other side, the Grocy maintainer is simply a rude person. I reported a couple of stuff on his side and I got almost spit on the face. So, don't ever wait for any actual fix coming from there, unless it is affecting HIS use case - which doesn't include HA, which he seems to almost despise.

Just noticed @berrnd actually left a laugh emoji on this. Nice. 🤦‍♂️ “If can’t say something nice, don’t say anything at all…”

**Comment by realcanadrian** [comment]
I think Home Assistant has an annual “month of WTH” or something where there is a push to fix a bunch of “WTH” type minor issues. I wonder if it would be possible to bring this to someone’s attention then.

**Comment by igorsantos07** [comment]
I told you, the Grocy maintainer is a complete a***ole. He's just interested in how the project benefits his uses, and doesn't seem to understand how open source walks once you put a project for other people to use. That's probably why Grocy is so ugly as well, no one will bother sending improvements for something he works so hard to keep walled to his own, small mind.

And it should be noted that he doesn't have any relationship with _this_ issue in special, since it's indeed HA-specific. But you can see how ugly is his behavior as he went out of his way to laugh at our complaints in something that has NOTHING for him to work on. Now, imagine his reactions on the issues he HAS stuff to do :clown_face:

**Comment by frenck** [comment]
Just woke up, noticed the response of @igorsantos07 which was completely out of bounds and violating CoC crossing it miles.

Everyone, including me, can have opinions, that is fine. I have a thick skin, and can handle some. But that crossed the line. I have therefore banned him from this org.

Once I have dragged my ass out of bed and had some coffee, I'll look at this issue.


../Frenck

**Comment by realcanadrian** [comment]
Thanks for your eyes on this @frenck. I know you’re extremely busy. Please accept my apologies for any part I had in fuelling the CoC violation.

**Comment by frenck** [comment]
Alright, so we ended up spending the day (national holiday in NL) with my family, so sorry for not getting back yesterday.

From my perspective, the core idea behind this issue is wrong.

> Since addon_config is available in Add-ons, we don't need to reinvent the wheels. Just make users customize their own config with addon_config option in Home Assistant. No need to make tweak for every option.

That sounds avoiding work, because we could just as well expose the source code? That is just wrong on many levels. Add-ons are supposed to make it easier to start using these extra applications next to Home Assistant.

That means, I think our parents should be able to just install and use this as well.Having to get a samba/ssh/vscode/whatever add-on, learn how to use a file editor, and learn how to edit (in this case) PHP files, is very much the opposite of that.

> With this change, someone who wants advanced features like label printer integration will customize their own config. No need to define every tweaks in config.yaml. 

That sounds tempting, but it also removes anyone (that is technical), to actually expose and make options available for non-technical users that can't do the above mentioned.

From that perspective, the suggestion made here, is harming the ecosystem and thus leaning towards this issue being a reason **not** to do it.

../Frenck

**Comment by realcanadrian** [comment]
Sorry for the delay responding to this. I'm glad you spent time with your family @frenck.

I completely understand the reasoning to keep things simple. Home Assistant should, as much as possible, work out of the box and be simple by default. However, I'm sure you will agree, another tenet of Home Assistant is to also allow (but not necessitate) more powerful customization for users as they become more savvy.

All I would ask is that the config be made _available_ somehow - perhaps in a directory mapped to the docker container or behind the "Show unused optional configuration options" toggle - so it _can_ be modified by those who are inclined. We absolutely don't want to complicate setup for basic users, but I feel it's also folly to prevent access to the app config for more experienced users.

Interested in your thoughts when you get a chance.

**Comment by frenck** [comment]
> However, I'm sure you will agree, another tenet of Home Assistant is to also allow (but not necessitate) more powerful customization for users as they become more savvy.

Honestly, if you need that, why not just go the Docker route directly?

**Comment by realcanadrian** [comment]
Any updates on this?
